"""Initial migration

Revision ID: e3d31375b7ae
Revises: 
Create Date: 2025-04-24 17:31:22.446910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3d31375b7ae'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('review')
    op.drop_table('creditcard')
    op.drop_table('clientaddress')
    with op.batch_alter_table('model', schema=None) as batch_op:
        batch_op.drop_index('idx_model_car')

    op.drop_table('model')
    op.drop_table('rent')
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.drop_index('idx_client_email')

    op.drop_table('client')
    op.drop_table('manager')
    op.drop_table('drivermodel')
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.drop_index('idx_car_id')

    op.drop_table('car')
    op.drop_table('address')
    with op.batch_alter_table('driver', schema=None) as batch_op:
        batch_op.drop_index('idx_driver_name')

    op.drop_table('driver')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('driver',
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('road', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('city', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['road', 'number', 'city'], ['address.road', 'address.number', 'address.city'], name='driver_road_number_city_fkey'),
    sa.PrimaryKeyConstraint('name', name='driver_pkey'),
    postgresql_ignore_search_path=False
    )
    with op.batch_alter_table('driver', schema=None) as batch_op:
        batch_op.create_index('idx_driver_name', ['name'], unique=False)

    op.create_table('address',
    sa.Column('road', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('city', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('road', 'number', 'city', name='address_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('car',
    sa.Column('carid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('brand', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('carid', name='car_pkey'),
    postgresql_ignore_search_path=False
    )
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.create_index('idx_car_id', ['carid'], unique=False)

    op.create_table('drivermodel',
    sa.Column('drivername', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('modelid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('carid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['drivername'], ['driver.name'], name='drivermodel_drivername_fkey'),
    sa.ForeignKeyConstraint(['modelid', 'carid'], ['model.modelid', 'model.carid'], name='drivermodel_modelid_carid_fkey'),
    sa.PrimaryKeyConstraint('drivername', 'modelid', 'carid', name='drivermodel_pkey')
    )
    op.create_table('manager',
    sa.Column('name', sa.VARCHAR(length=40), autoincrement=False, nullable=False),
    sa.Column('ssn', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('name', name='manager_pkey')
    )
    op.create_table('client',
    sa.Column('name', sa.VARCHAR(length=40), autoincrement=False, nullable=True),
    sa.Column('emailaddress', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('emailaddress', name='client_pkey'),
    postgresql_ignore_search_path=False
    )
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.create_index('idx_client_email', ['emailaddress'], unique=False)

    op.create_table('rent',
    sa.Column('rentid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('drivername', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('clientemail', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('modelid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('carid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['clientemail'], ['client.emailaddress'], name='rent_clientemail_fkey'),
    sa.ForeignKeyConstraint(['drivername'], ['driver.name'], name='rent_drivername_fkey'),
    sa.ForeignKeyConstraint(['modelid', 'carid'], ['model.modelid', 'model.carid'], name='rent_modelid_carid_fkey'),
    sa.PrimaryKeyConstraint('rentid', name='rent_pkey')
    )
    op.create_table('model',
    sa.Column('modelid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('constructionyear', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('color', sa.VARCHAR(length=40), autoincrement=False, nullable=True),
    sa.Column('transmissiontype', sa.VARCHAR(length=40), autoincrement=False, nullable=True),
    sa.Column('carid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['carid'], ['car.carid'], name='model_carid_fkey'),
    sa.PrimaryKeyConstraint('modelid', 'carid', name='model_pkey')
    )
    with op.batch_alter_table('model', schema=None) as batch_op:
        batch_op.create_index('idx_model_car', ['carid'], unique=False)

    op.create_table('clientaddress',
    sa.Column('emailaddress', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('road', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('city', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['emailaddress'], ['client.emailaddress'], name='clientaddress_emailaddress_fkey'),
    sa.ForeignKeyConstraint(['road', 'number', 'city'], ['address.road', 'address.number', 'address.city'], name='clientaddress_road_number_city_fkey'),
    sa.PrimaryKeyConstraint('emailaddress', 'road', 'number', 'city', name='clientaddress_pkey')
    )
    op.create_table('creditcard',
    sa.Column('cardnumber', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('clientemail', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('road', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('city', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['clientemail'], ['client.emailaddress'], name='creditcard_clientemail_fkey'),
    sa.ForeignKeyConstraint(['road', 'number', 'city'], ['address.road', 'address.number', 'address.city'], name='creditcard_road_number_city_fkey'),
    sa.PrimaryKeyConstraint('cardnumber', name='creditcard_pkey')
    )
    op.create_table('review',
    sa.Column('reviewid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('message', sa.CHAR(length=1), autoincrement=False, nullable=True),
    sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('drivername', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('clientemail', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['clientemail'], ['client.emailaddress'], name='review_clientemail_fkey'),
    sa.ForeignKeyConstraint(['drivername'], ['driver.name'], name='review_drivername_fkey'),
    sa.PrimaryKeyConstraint('reviewid', 'drivername', name='review_pkey')
    )
    # ### end Alembic commands ###
